const categoriesList = [
  { value: "bitcoin", label: "Bitcoin" },
  { value: "ethereum", label: "Ethereum" },
  { value: "crypto-indices", label: "Crypto Indices" },
  { value: "sub-coin", label: "Alt Coin" },
  { value: "on-chain", label: "On Chain" },
  { value: "sp500", label: "Sp500" },
  { value: "nasdaq", label: "Nasdaq" },
  { value: "Dax", label: "Dax" },
  { value: "dxy", label: "Dxy" },
  { value: "eur-usd", label: "Eur/Usd" },
  { value: "usd-jpy", label: "Usd/Jpy" },
  { value: "gold", label: "Gold" },
  { value: "silver", label: "Silver" },
  { value: "oil", label: "Oil" },
  { value: "coffee", label: "Coffee" },
  { value: "cotton", label: "Cotton" },
  { value: "live-cattle", label: "Live Cattle" },
  { value: "orange-juice", label: "Orange Juice" },
  { value: "soybean", label: "Soybean" },
  { value: "sugar", label: "Sugar" },
  { value: "wheat", label: "Wheat" },
  { value: "energy-etf", label: "Energy Etf" },
  { value: "natgas", label: "Natgas" },
  { value: "copper", label: "Copper" },
  { value: "aluminum", label: "Aluminum" },
  { value: "nickel", label: "Nickel" },
  { value: "paladium", label: "Paladium" },
  { value: "platinium", label: "Platinium" },
  { value: "aud-usd", label: "Aud/Usd" },
  { value: "gbp-usd", label: "Gbp/Usd" },
  { value: "nzd-usd", label: "Nzd/Usd" },
  { value: "usd-cad", label: "Usd/Cad" },
  { value: "usd-chf", label: "Usd/Chf" },
  { value: "asia", label: "Asia" },
  { value: "europa", label: "Europa" },
  { value: "usa", label: "Usa" },
];

export default categoriesList;
