const categoriesList = [
  { value: "bitcoin", label: "Bitcoin" },
  { value: "ethereum", label: "Ethereum" },
  { value: "crypto-indices", label: "Crypto Indices" },
  { value: "alt-coin", label: "Alt Coin" },
  { value: "on-chain", label: "On Chain" },
  { value: "sp500", label: "Sp500" },
  { value: "nasdaq", label: "Nasdaq" },
  { value: "dax", label: "Dax" },
  { value: "dxy", label: "Dxy" },
  { value: "eur-usd", label: "Eur/Usd" },
  { value: "usd-jpy", label: "Usd/Jpy" },
  { value: "gold", label: "Gold" },
  { value: "silver", label: "Silver" },
  { value: "oil", label: "Oil" },
  { value: "coffee", label: "Coffee" },
  { value: "cotton", label: "Cotton" },
  { value: "live-cattle", label: "Live Cattle" },
  { value: "orange-juice", label: "Orange Juice" },
  { value: "soybean", label: "Soybean" },
  { value: "sugar", label: "Sugar" },
  { value: "wheat", label: "Wheat" },
  { value: "energy-etf", label: "Energy Etf" },
  { value: "natgas", label: "Natgas" },
  { value: "copper", label: "Copper" },
  { value: "aluminum", label: "Aluminum" },
  { value: "nickel", label: "Nickel" },
  { value: "paladium", label: "Paladium" },
  { value: "platinium", label: "Platinium" },
  { value: "aud-usd", label: "Aud/Usd" },
  { value: "gbp-usd", label: "Gbp/Usd" },
  { value: "nzd-usd", label: "Nzd/Usd" },
  { value: "usd-cad", label: "Usd/Cad" },
  { value: "usd-chf", label: "Usd/Chf" },
  { value: "china50", label: "China50" },
  { value: "hongkong50", label: "Hongkong50" },
  { value: "nikkei", label: "Nikkei" },
  { value: "nse", label: "Nse" },
  { value: "cac40", label: "Cac40" },
  { value: "europa-dax", label: "Europa Dax" },
  { value: "ftse", label: "Ftse" },
  { value: "smi", label: "Smi" },
  { value: "stoxx50", label: "Stoxx50" },
  { value: "down-jones", label: "Downjones" },
  { value: "usa-sp500", label: "Usa Sp500" },
  { value: "usa-nasdaq", label: "Usa Nasdaq" },
  { value: "russell2000", label: "Russell2000" },
];

export default categoriesList;
